DESCRIPCION
Arquitectura y cálculo de la NN feedforward y backforward
Construir la arquitectura de una red neuronal.
Las entradas son 0,1, 0,2, 0,7
La salida esperada es 1.0. 0.0,0.0
Inicializar pesos de forma aleatoria (0.0 < peso < 1.0) o según ejemplo de clase (datos de pesos)
Inicializar los sesgos en 1.0

Detalles de la Arquitectura:
Construir una red neuronal Feed Forward con 2 capas ocultas (h1,h2).
Con 3 neuronas de salida output
Todas las capas tendrán 3 neuronas cada una.
La 1ª y 2ª capa oculta tendrán Relu y Sigmoide como funciones de activación.
La capa final de salida tendrá función de activación Softmax.

In [ ]:
import numpy as np#libreria a utilizar

Version con pesos fijos


Para la capa 1

In [ ]:
inputs1=np.array([0.1,0.2,0.7])
sesgos=np.array([1.0,1.0,1.0])

matriz1=np.array([[0.1 ,0.2 , 0.3],
                 [0.3,0.2,0.7],
                 [0.4,0.3,0.9]])

In [ ]:
compute=np.matmul(inputs1,matriz1)
z=compute+sesgos
z

array([1.35, 1.27, 1.8 ])

Para la capa 2

In [ ]:
inputs2=np.array([1.35,1.27,1.8])#son los valores de la capa anterior con relu
sesgos=np.array([1.0,1.0,1.0])

In [ ]:
matriz2=np.array([[0.2 ,0.3 , 0.5],
                 [0.3,0.5,0.7],
                 [0.6,0.4,0.8]])

In [ ]:
compute=np.matmul(inputs2,matriz2)

In [ ]:
z=compute+sesgos

In [ ]:
z

array([2.731, 2.76 , 4.004])

In [ ]:
# funcion sigmoide 
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


In [ ]:
ouputs=sigmoid(z)

In [ ]:
ouputs

array([0.93883129, 0.94047563, 0.9820843 ])

para la capa con softmax

In [ ]:
inputs3=np.array([0.938,0.94,0.98])#son los valores anteriormente obtenidos en la capa 2 con la funcion simoid
sesgos=np.array([1.0,1.0,1.0])

matriz3=np.array([[0.2 ,0.3 , 0.5],
                 [0.3,0.5,0.7],
                 [0.6,0.4,0.8]])

In [ ]:
compute=np.matmul(inputs3,matriz3)

In [ ]:
z=compute+sesgos
z

array([2.0576, 2.1434, 2.911 ])

In [ ]:
# funcion softmax
def softmax(x):

  e_x = np.exp(x - np.max(x))
  return e_x / e_x.sum(axis=0)

In [ ]:
ouputs=softmax(z)

In [ ]:
ouputs

array([0.22536717, 0.24555745, 0.52907538])

Version con pesos aleatorios

Para la capa 1

In [ ]:
import numpy as np

In [ ]:
inputs1=np.array([0.1,0.2,0.7])
sesgos=np.array([1.0,1.0,1.0])

np.random.seed(1)
matriz1=abs(np.random.random((3,3))-1) 
print(matriz1)

[[0.582978   0.27967551 0.99988563]
 [0.69766743 0.85324411 0.90766141]
 [0.81373979 0.65443927 0.60323253]]


In [ ]:
compute=np.matmul(inputs1,matriz1)
z=compute+sesgos
z

array([1.76744914, 1.65672386, 1.70378361])

Para la capa 2

In [ ]:

inputs2=z#son los valores de la capa anterior con relu
sesgos=np.array([1.0,1.0,1.0])
np.random.seed(1)
matriz2=abs(np.random.random((3,3))-1) 
print(matriz2)

[[0.582978   0.27967551 0.99988563]
 [0.69766743 0.85324411 0.90766141]
 [0.81373979 0.65443927 0.60323253]]


In [ ]:
compute=np.matmul(inputs2,matriz2)
z=compute+sesgos
z

array([4.57266275, 4.02292502, 5.29876899])

In [ ]:
# funcion sigmoide 
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


In [ ]:
ouputs=sigmoid(z)
ouputs

array([0.98977521, 0.98241427, 0.99502711])

Para la capa con sofmax

In [ ]:
inputs3=ouputs#son los valores de la capa anterior con sigmoid
sesgos=np.array([1.0,1.0,1.0])
np.random.seed(1)
matriz3=abs(np.random.random((3,3))-1) 
print(matriz3)

[[0.582978   0.27967551 0.99988563]
 [0.69766743 0.85324411 0.90766141]
 [0.81373979 0.65443927 0.60323253]]


In [ ]:
compute=np.matmul(inputs3,matriz3)
z=compute+sesgos
z

array([3.07210875, 2.76623989, 3.48159423])

In [ ]:
# funcion softmax
def softmax(x):

  e_x = np.exp(x - np.max(x))
  return e_x / e_x.sum(axis=0)

In [ ]:
ouputs=softmax(z)
z

array([3.07210875, 2.76623989, 3.48159423])